export const snValidatorMessage = {
	required: 'Preenchimento obrigatório',
	openingHours: '[00:01] - [23:59]',
	fromLowerThanTo: 'Horario de fechamento deve ser maior que o de abertura.',
	length: '[{length}] caracteres obrigatórios',
	minLength: 'Mínimo de [{minLength}] dígitos obrigatórios',
	maxLength: 'Máximo de [{maxLength}] dígitos obrigatórios',
	lengthBetween: 'Dígitos entre [{min}-{max}] obrigatório',
	value: 'Valor de [{value}] obrigatório',
	minValue: 'Valor mínimo de [{minValue}] obrigatório',
	maxValue: 'Valor mínimo de [{maxValue}] obrigatório',
	valueBetween: 'Valor entre [{min}-{max}] obrigatório',
	equalsTo: 'Valor esta diferente do campo [{equalsTo}]',
	enum: 'Valor não correspondido',
	isDate: 'Data [dia/mês/ano] obrigatória. Ex: [01/01/2023]',
	date: 'Data [dia/mês/ano] obrigatória. Ex: [01/01/2023]',
	minDate: 'Data minima [{minDate}] obrigatória',
	maxDate: 'Data máxima [{maxDate}] obrigatória',
	time: 'Horário [{time}] obrigatória',
	minTime: 'Horário minima [{minTime}] obrigatória',
	maxTime: 'Horário máximo [{maxTime}] obrigatória',
	datetime: 'Data&Horário [{datetimr}] obrigatória',
	minDateTime: 'Data&Horário minima [{minDatetime}] obrigatória',
	maxDateTime: 'Data&Horário máximo [{maxDatetime}] obrigatória',
}
